name: resume_parser
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - astunparse==1.6.3
      - cachetools==6.2.3
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - cryptography==46.0.3
      - exceptiongroup==1.3.1
      - fastapi==0.124.4
      - flatbuffers==25.9.23
      - gast==0.7.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - idna==3.11
      - keras==2.15.0
      - libclang==18.1.1
      - markdown==3.10
      - markupsafe==3.0.3
      - ml-dtypes==0.3.2
      - numpy==1.26.4
      - oauthlib==3.3.1
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - packaging==25.0
      - pdf2image==1.17.0
      - pdfminer-six==20251107
      - pdfplumber==0.11.8
      - pillow==12.0.0
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pypdf2==3.0.1
      - pypdfium2==5.2.0
      - pytesseract==0.3.13
      - python-multipart==0.0.20
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - six==1.17.0
      - starlette==0.50.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-intel==2.15.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.2.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - uvicorn==0.38.0
      - werkzeug==3.1.4
      - wrapt==1.14.2
prefix: C:\Users\bp611\anaconda3\envs\resume_parser
